### ISSUE TITLE
Vault Config Operator + Vault Quay Plugin not working as expected

### ISSUE THREAD

**Issue by rafaeltuelho** [redhat-cop/vault-plugin-secrets-quay#59]
Assuming an instance of Hashicorp Vault with Vault Quay Plugin installed...

I created a secret at `secret/secrets/rhdh/registry-plugin` with `username` and `password` keys.

Then, on my OCP cluster with Vault Config Operator installed I defined 
```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuaySecretEngineConfig
metadata:
  name: quay-io
  namespace: vault-admin
spec:
  authentication:
    path: kubernetes
    role: policy-admin
    serviceAccount:
      name: default
  disableSslVerification: true
  path: quay
  rootCredentials:
    passwordKey: password
    usernameKey: username
    vaultSecret:
      path: secret/secrets/rhdh/registry-plugin
  url: 'https://quay.io'
```

The, when I try to read from the quay vault secret plugin

```
vault read quay/creds/spring-boot-app
Error reading quay/creds/spring-boot-app: Error making API request.

URL: GET https://vault-vault.apps.cluster-6kknq.6kknq.sandbox63.opentlc.com/v1/quay/creds/spring-boot-app
Code: 500. Errors:

* 1 error occurred:
    * rpc error: code = Unavailable desc = error reading from server: EOF
```

interestingly is that the account is being created on my quay org.

logs on vault pod
```
2023-11-06T20:10:33.388Z [ERROR] secrets.vault-plugin-secrets-quay.vault-plugin-secrets-quay_93b6cf90.vault-plugin-secrets-quay: plugin process exited: path=/usr/local/libexec/vault/vault-plugin-secrets-quay-linux-amd64 pid=70405 error="exit status 2"
1267320
```

logs on vault-config-operator pod:

```
2023-11-06T19:56:34Z ERROR unable to read object at {"controller": "vaultsecret", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "VaultSecret", "VaultSecret": {"name":"registry-credentials","namespace":"spring-boot-app-dev"}, "namespace": "spring-boot-app-dev", "name": "registry-credentials", "reconcileID": "ac1a6057-eff6-4c0f-a236-049e9fc6bd4a", "path": "quay/creds/spring-boot-app", "error": "Error making API request.\n\nURL: GET https://vault.vault.svc:8200/v1/quay/creds/spring-boot-app\nCode: 500. Errors:\n\n* 1 error occurred:\n\t* rpc error: code = Unavailable desc = error reading from server: EOF\n\n"}
63819github.com/redhat-cop/vault-config-operator/api/v1alpha1/utils.ReadSecret
63820/home/runner/work/vault-config-operator/vault-config-operator/api/v1alpha1/utils/vaultutils.go:74
63821github.com/redhat-cop/vault-config-operator/api/v1alpha1/utils.(*VaultSecretEndpoint).GetSecret
63822/home/runner/work/vault-config-operator/vault-config-operator/api/v1alpha1/utils/vaultsecretobject.go:29
```
